---
- name: Install Nano
  package:
    name: "nano"
    state: installed
  become: yes
  
- name: Install Wget
  package:
    name: "wget"
    state: installed
  become: yes

- name: Install Unzip
  package:
    name: "unzip"
    state: installed
  become: yes